DocTr/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('core.urls', namespace='core')),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^consultas/', include('consult.urls', namespace='consult')),
    url(r'^registros/', include('register.urls', namespace='register')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

core/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = patterns('',...)

urlpatterns = [
    
    url(r'^$', 'core.views.home', name='home'),
    url(r'^rest', 'core.views.rest', name='rest'),
    url(r'^cadastrar_medico', 'core.views.register_doctor', name='register_doctor'),
    url(r'^cadastrar_pacitente', 'core.views.register_patient', name='register_patient'),
    url(r'^escolha_cadastro', 'core.views.choice_register', name='choice_register'),
    url(r'^login', 'django.contrib.auth.views.login',{'template_name': 'login.html'}, name='login'),
    url(r'^sair/$', 'django.contrib.auth.views.logout',{'next_page': 'core:login'}, name='logout'),
    url(r'^favicon\.ico$', RedirectView.as_view(url='{{STATIC_URL}}/assets/img/icon.png'))
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

register/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = patterns('',...)

urlpatterns = [
    url(r'^$', 'register.views.registers', name='registers'),
    url(r'^criar_exames_consulta(?P<slug>[\w_-]+)', 'register.views.creat_register_consult_exams', name='creat_register_consult_exams'),
    url(r'^criar_tratamento_consulta(?P<slug>[\w_-]+)', 'register.views.creat_register_consult_treatments', name='creat_register_consult_treatments'),
    url(r'^(?P<slug>[\w_-]+)/escolha_registro', 'register.views.choice_register', name='choice_register'),
   	url(r'^(?P<slug>[\w_-]+)/exames', 'register.views.exams', name='exams'),
   	url(r'^(?P<slug>[\w_-]+)/tratamentos', 'register.views.treatments', name='treatments'),
    url(r'^registros_da_consulta', 'register.views.consult_register', name='consult_register'),
    url(r'^(?P<slug>[\w_-]+)/registro_detalhe', 'register.views.details_register', name='details_register'),
    url(r'^(?P<slug>[\w_-]+)/exame_detalhe', 'register.views.details_exams', name='details_exam'),
    url(r'^(?P<slug>[\w_-]+)/tratamento_detalhe', 'register.views.details_treatments', name='details_treatment'),



]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

register/models.py
from django.db import models
from django.conf import settings
from django.db.models import signals
from datetime import date
from django.template.defaultfilters import slugify
from accounts.models import Patient


class RegisterManager(models.Manager):

    def search(self,query):
        return self.get_queryset().filter(
            models.Q(Register__icontains=query) | \
            models.Q(description__icontains=query)

)
class Register(models.Model):

    register_code = models.IntegerField('ID',primary_key=True, null=False, blank=False)
    about = models.TextField('Mais informações', blank = True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)
    slug = models.SlugField('Atalho', max_length = 150, editable=True)

    consult = models.ForeignKey("consult.Doctor_consult", verbose_name='Consulta',
        related_name='register_Consult'
    )

    def __str__(self):
        return self.register_code

    def save(self, *args, **kwargs):
        self.slug = slugify(self.register_code)
        super(Register, self).save(*args, **kwargs)

    def set_ativo(self):
        self.status = 0
        self.save()

    def set_encerrado(self):
        self.status = 1
        self.save()

    def set_declassificado(self):
        self.status = 2
        self.save()

    def set_arquivado(self):
        self.status = 3
        self.save()

    def is_ativo(self):
        return self.status == 0

    def is_encerrado(self):
        return self.status == 1

    def is_desclassificado(self):
        return self.status == 2

    def is_arquivado(self):
        return self.status == 3

    @models.permalink
    def get_absolute_url(self):
        return('register:details_register', (), {'slug': self.slug})

    class Meta:
        verbose_name = 'Registro'
        verbose_name_plural = 'Registros'
        ordering = ['register_code']

class Exams(Register):

    result = models.TextField('Resultado do Exame', max_length= 50,null=True,blank=True)

    def __str__(self):
        return "Exame -> " + self.result or "Exame -> padrão"

    def get_short_name(self):
        return self.result

    def get_full_name(self):
        return str(self)

    @models.permalink
    def get_absolute_url(self):
        return('register:details_exams', (), {'slug': self.slug})


    class Meta:
        verbose_name = 'Exame'
        verbose_name_plural = 'Exames'

class Medicine(models.Model):

    name = models.CharField('Nome do medicamento', max_length= 50,null=False, primary_key=True)

    def __str__(self):
        return self.name

    def get_short_name(self):
        return self.name

    def get_full_name(self):
        return str(self)

    class Meta:
        verbose_name = 'Medicamento'
        verbose_name_plural = 'Medicamentos'


class Treatment(Register):

    medicine = models.ManyToManyField(Medicine, verbose_name='Medicamento',
        related_name='medicine_Treatment', blank=True
    )

    def __str__(self):
        return "Tratamento -> " + self.about or "Tratamento -> padrão"

    def get_short_name(self):
        return self.about

    def get_full_name(self):
        return str(self)

    @models.permalink
    def get_absolute_url(self):
        return('register:details_treatments', (), {'slug': self.slug})

    class Meta:
        verbose_name = 'Tratamento'
        verbose_name_plural = 'Tratamentos'

register/forms.py
# -*- coding: utf8 -*-
from django import forms
from .models import *
# SIGNALS
from django.db.models import signals
from django.template.defaultfilters import slugify
from accounts.models import *
import datetime
import DocTr.settings

class RegisterFormExams(forms.ModelForm):

	class Meta:
		model = Exams
		fields = ['about', 'result', 'register_code']

class RegisterFormTreatments(forms.ModelForm):

	class Meta:
		model = Treatment
		fields = ['about', 'medicine', 'register_code']

# class Edit_EventoForm(forms.ModelForm):

# 	def evento_pre_save(signal, instance, sender, **kwargs):
# 		instance.slug = slugify(instance.name)
# 	signals.pre_save.connect(evento_pre_save, sender = Evento)

# 	def clean_valor(self):
# 		valor = self.cleaned_data['valor']
# 		if valor <= 0:
# 			raise forms.ValidationError('O valor não pode ser menor ou igual a zero')
# 		return  valor
# 	class Meta:
# 		model = Evento
# 		fields = ['name', 'place_event','date_event','date_event_finsh','start_date_errolment',
# 			'finsh_date_enrrolment','image','about','valor', 'pares']

register/views.py
# -*- coding: utf8 -*-
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.http import HttpResponseRedirect
from .models import *
from accounts.models import *
from consult.models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import *
from django.contrib.auth import get_user
import datetime
import copy
from .models import *
# SIGNALS AND LISTENERS
from django.contrib.auth.models import User
from django.db.models import signals
from django.dispatch import dispatcher
# EXTRAS
from datetime import date


@login_required(redirect_field_name='login_obrigatorio')
def creat_register_consult_exams(request,slug):
	
	template_name = 'creat_register_consult_exams.html'
	consult = get_object_or_404(Consult, slug = slug)
	form = RegisterFormExams(request.POST, request.FILES)
	contexto = {}
	if request.method == "POST":
		if form.is_valid():
			newform = form.save(commit=False)
			newform.user = request.user
			newform.consult = consult
			newform.register_code = newform.register_code + 1
			newform.save()
			messages.success(request,'Exame criado com sucesso!')
			form = RegisterFormExams()
	else:
		print('Não')
		form = RegisterFormExams()
	contexto['form'] = form
	contexto['hospital'] = consult.hospital
	contexto['doctor'] = consult.doctor
	contexto['patient'] = consult.patient
	contexto['consult'] = consult
	contexto['slug'] = slug
	return render(request, template_name,contexto)

@login_required(redirect_field_name='login_obrigatorio')
def creat_register_consult_treatments(request,slug):

	template_name = 'creat_register_consult_treatments.html'
	consult = get_object_or_404(Consult, slug = slug)
	form = RegisterFormTreatments(request.POST, request.FILES)
	contexto = {}
	if request.method == "POST":
		if form.is_valid():
			newform = form.save(commit=False)
			newform.user = request.user
			newform.consult = consult
			newform.register_code = newform.register_code + 1
			newform.save()
			messages.success(request,'Tratamento criado com sucesso!')
			form = RegisterFormTreatments()
	else:
		print('Não')
		form = RegisterFormTreatments()
	contexto['form'] = form
	contexto['hospital'] = consult.hospital
	contexto['doctor'] = consult.doctor
	contexto['patient'] = consult.patient
	contexto['consult'] = consult
	contexto['slug'] = slug
	return render(request, template_name,contexto)

@login_required(redirect_field_name='login_obrigatorio')
def registers(request):
	template_name = ''
	contexto = {}
	consults = None
	try:
		doctor = Doctor.objects.get(id = request.user.id)
		registers = Register.objects.all()
		template_name = 'registers.html'
	except Exception as e:
		patient = Patient.objects.get(id = request.user.id)
		registers = Doctor_consult.objects.all().filter(patient = patient)
		print('Paciente Registro')
		template_name = 'register_patient.html'
	contexto = {
		'registers':registers
	}
	return render(request, template_name, contexto)

@login_required(redirect_field_name='login_obrigatorio')
def consult_register(request):
	consult_register = Register.objects.all()
	template_name = 'consult_register.html'
	contexto = {
		'consult_register':consult_register
	}
	return render(request, template_name, contexto)

@login_required(redirect_field_name='login_obrigatorio')
def details_register(request, slug):
    template_name = 'details_register.html'
    context = {
    	'slug': slug
    }
    return render(request, template_name,context)

@login_required(redirect_field_name='login_obrigatorio')
def choice_register(request, slug):
    template_name = 'choice_register.html'
    context = {
    	'slug': slug
    }
    return render(request, template_name,context)

@login_required(redirect_field_name='login_obrigatorio')
def exams(request, slug):
    template_name = 'exams.html'
    exams = Exams.objects.all()
    context = {
    	'exams':exams,
    	'slug':slug
    }
    return render(request, template_name,context)
@login_required(redirect_field_name='login_obrigatorio')
def treatments(request, slug):
    template_name = 'treatments.html'
    treatments = Treatment.objects.all()
    context = {
    	'treatments':treatments,
    	'slug':slug
    }
    return render(request, template_name,context)

@login_required(redirect_field_name='login_obrigatorio')
def details_treatments(request, slug):
	template_name = 'details_treatments.html'
	treatments = get_object_or_404(Treatment,slug = slug)
	context = {
		'slug': slug,
		'treatment': treatments
	}
	return render(request, template_name,context)

@login_required(redirect_field_name='login_obrigatorio')
def details_exams(request, slug):

	exams = get_object_or_404(Exams,slug = slug)
	template_name = 'details_exams.html'
	context = {
		'slug': slug,
		'exam':exams
	}
	return render(request, template_name,context)

register/templates/choice_register.html
{% extends 'doctor/dashboard_doctor.html' %}
{% load static %}
<html>
  <head>
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
  <style type="text/css">
    #botao{
      margin-top: -10%;
    }
  </style>
    <div class="wrapper">
      <!-- Left side column. contains the logo and sidebar -->
      {% block content %}
        {% block shortcuts %}
            {{ block.super }}
              
            <div class="col-md-12">
              <div class="box">
                <div class="box-header with-border">
                  <br>
                  <center><h3 class="box-title">Escolher tipo de registro</h3></center>
                  <br>
                </div><!-- /.box-header -->
              </div><!-- /.box -->
            </div><!-- /.col -->
            <a href="{% url 'register:exams' slug %}">Exames</a>
            <a href="{% url 'register:treatments' slug %}">Tratamentos</a>
            </div>
            </div>
        {% endblock %}
      {% endblock %}
    </div><!-- ./wrapper -->

  </body>
</html>

register/templates/consult_register.html
{% extends 'doctor/dashboard_doctor.html' %}
{% load static %}
<html>
  <head>
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
  <style type="text/css">
    #botao{
      margin-top: -10%;
    }
  </style>
    <div class="wrapper">
      <!-- Left side column. contains the logo and sidebar -->
      {% block content %}
        {% block shortcuts %}
            {{ block.super }}

            <div class="col-md-12">
              <div class="box">
                <div class="box-header with-border">
                  <br>
                  <center><h3 class="box-title">Lista de regitros da consulta:
                    {% for register in consult_register %}
                      {{register.consult.consult_code}}
                    {% endfor %}
                      </h3></center>
                    
                  <br>

                  <form class="col-md-12 col-lg-offset-10">
                  <h4>Criar registro</h4>
                    <div class="input-group">
                      <div class="input-group-btn">
                      <a href="{% url 'register:choice_register' %}"><button class="btn btn-success" type="button"><i class="fa fa-plus"></i></button></a>
                      </div>
                    </div>
                  </form>

                </div><!-- /.box-header -->
                {% for register in consult_register %}
                <div class="box-body">
                  <table class="table table-bordered">
                    <tr>
                      <th>Código</th>
                      <th>Tipo de registro</th>
                      <th>Médico</th>
                      <th>Data</th>
                      <th>Hospital</th>
                      <th>Mais informações</th>
                      <th>...</th>
                    </tr>
                    <tr>
                      <td>{{register.register_code}}</td>
                      <td>{{register.register_type}}</td>
                      <td>{{register.consult.doctor}}</td>
                      <td><span class="badge bg-red">{{register.date_register}}</span></td>
                      <td>{{register.hospital}}</td>
                      <td>{{register.about}}</td>
                      <td>
                        <div class="input-group">
                          <div class="input-group-btn">
                            <a href="{{ register.get_absolute_url }}"><button class="btn btn-success" type="button">Visualizar</button></a>
                          </div>
                        </div>
                      </td>
                    </tr>
                  </table>
                </div><!-- /.box-body -->
                {% empty %}
                <h2><center>Nenhum registro</center></h2>
                {% endfor %}
                <div class="box-footer clearfix">
                  <ul class="pagination pagination-sm no-margin pull-right">
                    <li><a href="#">&laquo;</a></li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">&raquo;</a></li>
                  </ul>
                </div>
              </div><!-- /.box -->
            </div><!-- /.col -->

		</div>  
    </div>
        {% endblock %}
      {% endblock %}
    </div><!-- ./wrapper -->

  </body>
</html>

register/templates/creat_register_consult.html
{% extends 'dashboard.html' %}
{% load static %}
{% load widget_tweaks %}
<html>
  <head>
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
  <style type="text/css">

  </style>
    <div class="wrapper">
      <!-- Left side column. contains the logo and sidebar -->
      {% block content %}
        {% block shortcuts %}
            {{ block.super }}
              
            <div class="col-md-12">
              <div class="box">
                <div class="box-header with-border">
                  <br>
                  <center><h3 class="box-title">Criar de registro</h3></center>
                  <br>
                </div><!-- /.box-header -->

              </div><!-- /.box -->
            </div><!-- /.col -->
            <div class="col-md-12">
            {% if messages %}
              {% for message in messages %}
                <div class="ale" >
                    <h4><div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <center>{{ message|safe }}</center>
                  </div>
                  </h4>
                  </div>
              {% endfor %}
            {% endif %}
              <div class="box box-primary">
                  <div class="box-header with-border">
                    <h3 class="box-title">Coloque os dados da consulta</h3>
                  </div><!-- /.box-header -->
                  <!-- form start -->
                  <form method="post">{% csrf_token %}
                    <div class="box-body">
                      <div class="form-group">
                        <label for="exampleInputEmail1">Código da Consulta</label>
                        {{ form.non_field_errors }}
                        {{ form.consult_code|attr:"type:text"|attr:"placeholder:Código da consulta"|add_class:"form-control"}}
                        {{ form.consult_code.errors|add_error_class:"error-border"}}
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Tipo de Consulta</label>
                        {{ form.non_field_errors }}
                        {{ form.consult_type|attr:"type:text"|attr:"placeholder:Tipo de consulta"|add_class:"form-control"}}
                        {{ form.consult_type.errors|add_error_class:"error-border"}}
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Hospital</label>
                        {{ form.non_field_errors }}
                        {{ form.hospital|attr:"type:text"|attr:"placeholder:Hospital"|add_class:"form-control"}}
                        {{ form.hospital.errors|add_error_class:"error-border"}}
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Data e hora</label>
                        {{ form.non_field_errors }}
                        {{ form.date_consult|attr:"type:date"|attr:"placeholder:Data e hora"|add_class:"form-control"}}
                        {{ form.date_consult.errors|add_error_class:"error-border"}}
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Médico</label>
                        {{ form.non_field_errors }}
                        {{ form.doctor|attr:"type:select"|attr:"placeholder:Tipo de consulta"|add_class:"form-control"}}
                        {{ form.doctor.errors|add_error_class:"error-border"}}
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Paciente</label>
                        {{ form.non_field_errors }}
                        {{ form.patient|attr:"type:select"|attr:"placeholder:Tipo de consulta"|add_class:"form-control"}}
                        {{ form.patient.errors|add_error_class:"error-border"}}
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Mais informações</label>
                        {{ form.non_field_errors }}
                        {{ form.about|attr:"type:textarea"|attr:"placeholder:Escreva informações extras"|add_class:"form-control"}}
                        {{ form.about.errors|add_error_class:"error-border"}}
                      </div>
                      
                    </div><!-- /.box-body -->

                    <div class="box-footer">
                      <button type="submit" class="btn btn-primary">Criar</button>
                    </div>
                  </form>
                </div><!-- /.box -->
              </div>
              </div>
            </div>
        {% endblock %}
      {% endblock %}
    </div><!-- ./wrapper -->

  </body>
</html>

register/templates/details_exams.html
{% extends 'doctor/dashboard_doctor.html' %}
{% load static %}
<html>
  <head>
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
  <style type="text/css">
    #botao{
      margin-top: -10%;
    }
  </style>
    <div class="wrapper">
      <!-- Left side column. contains the logo and sidebar -->
      {% block content %}
        {% block shortcuts %}
            {{ block.super }}
              
            <div class="col-md-12">
              <div class="box">
                <div class="box-header with-border">
                  <br>
                  <center><h3 class="box-title">Detalhes do Exame: {{slug}}</h3></center>
                  <br>
                </div><!-- /.box-header -->                
              </div><!-- /.box -->
            </div><!-- /.col -->

            <div class="col-md-12">
              <ul class="timeline">
                <li>
                  <div class="timeline-item" id="itemt">
                    <h3 class="timeline-header no-border"><center>Fotos</center></h3>
                  </div>
                </li>
              </ul>
            </div>
            <!-- row -->
          <div class="row">
            <div class="col-md-12">
              <!-- The time line -->
              <ul class="timeline">
                <li>
                  <i class="fa fa-camera bg-purple"></i>
                  <div class="timeline-item">
                    <span class="time"><i class="fa fa-clock-o"></i> 2 days ago</span>
                    <h3 class="timeline-header"><a href="#">{{exam.consult.patient.name}}</a> fez upload das seguintes fotos</h3>
                    <div class="timeline-body">
                      <img src="http://placehold.it/150x100" alt="..." class="margin">
                      <img src="http://placehold.it/150x100" alt="..." class="margin">
                      <img src="http://placehold.it/150x100" alt="..." class="margin">
                      <img src="http://placehold.it/150x100" alt="..." class="margin">
                    </div>
                  </div>
                </li>
              <ul/>
            </div><!-- /.col -->
          </div>
                <!-- END timeline item -->
                <!-- timeline item -->
                <div class="col-md-12">
                  <ul class="timeline">
                    <li>
                      <div class="timeline-item">
                        <h3 class="timeline-header no-border" id="nome"><center>Resultado</center></h3>
                      </div>
                    </li>
                  </ul>
                </div>
         <div class="row">
            <div class="col-md-12">
                <ul class="timeline">
                <li>
                  <i class="fa fa-info bg-maroon"></i>
                  <div class="timeline-item">
                    <span class="time"><i class="fa fa-clock-o"></i> 5 days ago</span>
                    <h3 class="timeline-header"><a href="#">{{exam.consult.patient.name}}</a> possui o seguinte resultado do exame</h3>
                    <div class="timeline-body">
                      <div class="embed-responsive embed-responsive-16by9">
                        <p><h4>{{exam.result}}</h4></p>
                      </div>
                    </div>
                  </div>
                </li>
                <!-- END timeline item -->
              </ul>
            </div><!-- /.col -->
          </div><!-- /.row -->
            </div>
            </div>
        {% endblock %}
      {% endblock %}
    </div><!-- ./wrapper -->

  </body>
</html>

register/templates/exams.html
{% extends 'doctor/dashboard_doctor.html' %}
{% load static %}
<html>
  <head>
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
  <style type="text/css">
    #botao{
      margin-top: -10%;
    }
  </style>
    <div class="wrapper">
      <!-- Left side column. contains the logo and sidebar -->
      {% block content %}
        {% block shortcuts %}
            {{ block.super }}
              
            <div class="col-md-12">
              <div class="box">
                <div class="box-header with-border">
                  <br>
                  <center><h3 class="box-title">Lista de exames da consulta : </h3></center>
                  <br>
                  <form class="col-md-12 col-lg-offset-10">
                  <h4>Criar exame</h4>
                    <div class="input-group">
                      <div class="input-group-btn">
                        <a href="{% url 'register:creat_register_consult_exams' slug %}"><button class="btn btn-success" type="button"><i class="fa fa-plus"></i></button></a>
                      </div>
                    </div>
                  </form>
                  {% for exam in exams %}
              <div class="box-body">
                <table class="table table-bordered">
                  <tr>
                    <th>Paciente</th>
                    <th>Médico</th>
                    <th>Data e Hora</th>
                    <th>Hospital</th>
                    <th>Resultado</th>
                    <th>Mais informações</th>
                  </tr>
                  <tr>
                    <td>{{exam.consult.patient}}</td>
                    <td>{{exam.consult.doctor}}</td>
                    <td><span class="badge bg-red">{{exam.created_at}}</span></td>
                    <td>{{exam.consult.hospital}}</td>
                    <td>{{exam.result}}</td>
                    <td>
                      <div class="input-group">
                        <div class="input-group-btn">
                          <a href="{{ exam.get_absolute_url }}"><button class="btn btn-success" type="button">Ver detahes</button></a>
                        </div>
                      </div>
                    </td>
                  </tr>
                </table>
              </div><!-- /.box-body -->
              {% endfor %}
              <div class="box-footer clearfix">
                <ul class="pagination pagination-sm no-margin pull-right">
                  <li><a href="#">&laquo;</a></li>
                  <li><a href="#">1</a></li>
                  <li><a href="#">2</a></li>
                  <li><a href="#">3</a></li>
                  <li><a href="#">&raquo;</a></li>
                </ul>
              </div>

                </div><!-- /.box-header -->
              </div><!-- /.box -->
            </div><!-- /.col -->  
            
            </div>
            </div>
        {% endblock %}
      {% endblock %}
    </div><!-- ./wrapper -->

  </body>
</html>

register/templates/treatments.html
{% extends 'doctor/dashboard_doctor.html' %}
{% load static %}
<html>
  <head>
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
  <style type="text/css">
    #botao{
      margin-top: -10%;
    }
  </style>
    <div class="wrapper">
      <!-- Left side column. contains the logo and sidebar -->
      {% block content %}
        {% block shortcuts %}
            {{ block.super }}
              
            <div class="col-md-12">
              <div class="box">
                <div class="box-header with-border">
                  <br>
                  <center><h3 class="box-title">Lista de Tratamentos</h3></center>
                  <br>
                  <form class="col-md-12 col-lg-offset-10">
                  <h4>Criar Tratamento</h4>
                    <div class="input-group">
                      <div class="input-group-btn">
                        <a href="{% url 'register:creat_register_consult_treatments' slug %}"><button class="btn btn-success" type="button"><i class="fa fa-plus"></i></button></a>
                      </div>
                    </div>
                  </form>
                  {% for treatment in treatments %}
              <div class="box-body">
                <table class="table table-bordered">
                  <tr>
                    <th>Paciente</th>
                    <th>Médico</th>
                    <th>Data e Hora</th>
                    <th>Hospital</th>
                    <th>Resultado</th>
                    <th>Mais informações</th>
                  </tr>
                  <tr>
                    <td>{{treatment.consult.patient}}</td>
                    <td>{{treatment.consult.doctor}}</td>
                    <td><span class="badge bg-red">{{treatment.created_at}}</span></td>
                    <td>{{treatment.consult.hospital}}</td>
                    <td>{{treatment.result}}</td>
                    <td>
                      <div class="input-group">
                        <div class="input-group-btn">
                          <a href="{{ treatment.get_absolute_url }}"><button class="btn btn-success" type="button">Ver detahes</button></a>
                        </div>
                      </div>
                    </td>
                  </tr>
                </table>
              </div><!-- /.box-body -->
              {% endfor %}
              <div class="box-footer clearfix">
                <ul class="pagination pagination-sm no-margin pull-right">
                  <li><a href="#">&laquo;</a></li>
                  <li><a href="#">1</a></li>
                  <li><a href="#">2</a></li>
                  <li><a href="#">3</a></li>
                  <li><a href="#">&raquo;</a></li>
                </ul>
              </div>
                </div><!-- /.box-header -->
              </div><!-- /.box -->
            </div><!-- /.col -->

            </div>
            </div>
        {% endblock %}
      {% endblock %}
    </div><!-- ./wrapper -->

  </body>
</html>