DocTr/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('core.urls', namespace='core')),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^consultas/', include('consult.urls', namespace='consult')),
    url(r'^registros/', include('register.urls', namespace='register')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

consult/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = patterns('',...)

urlpatterns = [

    url(r'^$', 'consult.views.consults', name='consults'),
    url(r'^criar_consulta', 'consult.views.create_consult', name='create_consult'),
    url(r'^(?P<slug>[\w_-]+)/consulta_detalhe', 'consult.views.details_consult', name='details_consult'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = patterns('',...)

urlpatterns = [
    
    url(r'^$', 'core.views.home', name='home'),
    url(r'^rest', 'core.views.rest', name='rest'),
    url(r'^cadastrar_medico', 'core.views.register_doctor', name='register_doctor'),
    url(r'^cadastrar_pacitente', 'core.views.register_patient', name='register_patient'),
    url(r'^escolha_cadastro', 'core.views.choice_register', name='choice_register'),
    url(r'^login', 'django.contrib.auth.views.login',{'template_name': 'login.html'}, name='login'),
    url(r'^sair/$', 'django.contrib.auth.views.logout',{'next_page': 'core:login'}, name='logout'),
    url(r'^favicon\.ico$', RedirectView.as_view(url='{{STATIC_URL}}/assets/img/icon.png'))
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

register/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = patterns('',...)

urlpatterns = [
    url(r'^$', 'register.views.registers', name='registers'),
    url(r'^criar_exames_consulta(?P<slug>[\w_-]+)', 'register.views.creat_register_consult_exams', name='creat_register_consult_exams'),
    url(r'^criar_tratamento_consulta(?P<slug>[\w_-]+)', 'register.views.creat_register_consult_treatments', name='creat_register_consult_treatments'),
    url(r'^(?P<slug>[\w_-]+)/escolha_registro', 'register.views.choice_register', name='choice_register'),
   	url(r'^(?P<slug>[\w_-]+)/exames', 'register.views.exams', name='exams'),
   	url(r'^(?P<slug>[\w_-]+)/tratamentos', 'register.views.treatments', name='treatments'),
    url(r'^registros_da_consulta', 'register.views.consult_register', name='consult_register'),
    url(r'^(?P<slug>[\w_-]+)/registro_detalhe', 'register.views.details_register', name='details_register'),
    url(r'^(?P<slug>[\w_-]+)/exame_detalhe', 'register.views.details_exams', name='details_exam'),
    url(r'^(?P<slug>[\w_-]+)/tratamento_detalhe', 'register.views.details_treatments', name='details_treatment'),



]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

consult/models.py
from django.db import models
from django.conf import settings
from django.db.models import signals
from datetime import date
from django.template.defaultfilters import slugify
from accounts.models import Patient


class ConsultManager(models.Manager):

	def search(self,query):

		return self.get_queryset().filter(
		models.Q(consult__icontains=query) | \
		models.Q(description__icontains=query)

		)
class Consult(models.Model):

    consult_code = models.CharField('Código da Consulta', max_length=100, null=False, unique=True, primary_key=True)
    consult_type = models.CharField('Tipo de Consulta', max_length = 100)
    hospital = models.CharField('Hospital', max_length= 50)
    slug = models.SlugField('Atalho', max_length = 150, editable=True)
    about = models.TextField('Mais informações', blank = True)
    date_consult = models.DateTimeField('Data que está marcada a Consulta',auto_now_add=True, blank=True, null=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    doctor = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='Médico',
        related_name='consult_médico'
    )

    def __str__(self):
        return self.consult_code

    def save(self, *args, **kwargs):
        self.slug = slugify(self.consult_code)
        super(Consult, self).save(*args, **kwargs)

    def set_ativo(self):
        self.status = 0
        self.save()

    def set_encerrado(self):
        self.status = 1
        self.save()

    def set_declassificado(self):
        self.status = 2
        self.save()

    def set_arquivado(self):
        self.status = 3
        self.save()

    def is_ativo(self):
        return self.status == 0

    def is_encerrado(self):
        return self.status == 1

    def is_desclassificado(self):
        return self.status == 2

    def is_arquivado(self):
        return self.status == 3

    @models.permalink
    def get_absolute_url(self):
        return('consult:details_consult', (), {'slug': self.slug})

    class Meta:
        verbose_name = 'Consulta'
        verbose_name_plural = 'Consultas'
        ordering = ['consult_type']

class Doctor_consult(models.Model):

    STATUS_CHOICES = (
        (0, 'Realizada'),
        (1, 'Pendente'),
        (2, 'Cancelada'),
        (3, 'Arquivada'),
    )

    doctor = models.ForeignKey('accounts.Doctor', verbose_name='Médico',
        related_name='doctor_consult_Doctor', on_delete=models.CASCADE
    )
    consult = models.ForeignKey(
        Consult, verbose_name='Consulta', related_name='doctor_consult_Consult', on_delete=models.CASCADE
    )
    patient = models.ForeignKey(
        Patient, verbose_name='Paciente',
        related_name='doctor_consult_Patient',blank = True, null=True, on_delete=models.CASCADE
    )
    status = models.IntegerField(
        'Situação', choices=STATUS_CHOICES, default=1, blank=True
    )

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    def __unicode__(self):
        return self.doctor + "->" + self.consult

    def set_pending(self):
        self.status = 0
        self.save()

    def set_active(self):
        self.status = 1
        self.save()

    def set_closed(self):
        self.status = 2
        self.save()

    def is_pending(self):
        return self.status == 0

    def is_approved(self):
        return self.status == 1

    def is_closed(self):
        return self.status == 2

    def __str__(self):
        return str(self.doctor) + " -> criou a consulta : " + str(self.consult)

    class Meta:
        verbose_name = 'Médico_Consulta'
        verbose_name_plural = 'Médicos_Consultas'
        unique_together = (('doctor', 'consult'),)

consult/forms.py
# -*- coding: utf8 -*-
from django import forms
from .models import *
# SIGNALS
from django.db.models import signals
from django.template.defaultfilters import slugify
from accounts.models import *
import datetime
import DocTr.settings


class ConsultForm(forms.ModelForm):
    class Meta:
        model = Doctor_consult
        fields = ['patient', 'doctor', 'consult']

    def __init__(self, *args, **kwargs):
        # consult = kwargs.pop('consult_code','')
        super(ConsultForm, self).__init__(*args, **kwargs)
        # self.fields['consult_type']=forms.ModelChoiceField(queryset=Consult.objects.filter(consult_code=consult))
        self.fields['hospital'] = forms.CharField(max_length=50)
        self.fields['consult_type'] = forms.CharField(max_length=100)
        self.fields['about'] = forms.CharField(max_length=100)
        self.fields['consult_code'] = forms.CharField(max_length=100)

        # class Edit_EventoForm(forms.ModelForm):

        # 	def evento_pre_save(signal, instance, sender, **kwargs):
        # 		instance.slug = slugify(instance.name)
        # 	signals.pre_save.connect(evento_pre_save, sender = Evento)

        # 	def clean_valor(self):
        # 		valor = self.cleaned_data['valor']
        # 		if valor <= 0:
        # 			raise forms.ValidationError('O valor não pode ser menor ou igual a zero')
        # 		return  valor
        # 	class Meta:
        # 		model = Evento
        # 		fields = ['name', 'place_event','date_event','date_event_finsh','start_date_errolment',
        # 			'finsh_date_enrrolment','image','about','valor', 'pares']

consult/views.py
# -*- coding: utf8 -*-
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.http import HttpResponseRedirect
from .models import *
from accounts.models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import *
from django.contrib.auth import get_user
from register.models import *
import datetime
import copy
from .models import *
# SIGNALS AND LISTENERS
from django.contrib.auth.models import User
from django.db.models import signals
from django.dispatch import dispatcher
# EXTRAS
from datetime import date


@login_required(redirect_field_name='login_obrigatorio')
def create_consult(request):

	template_name = 'create_consult.html'
	form = ConsultForm(request.POST, request.FILES)
	contexto = {}
	if request.method == "POST":
		if form.is_valid():
			newform = form.save(commit=False)
			newform.user = request.user
			patient = newform.patient
			print('1')
			newform.consult.consult_id = newform.consult.consult_code
			print('2')
			newform.consult = request.POST['consult_code']
			print('3')
			newform.save()
			slug = newform.consult.slug
			consult = get_object_or_404(Consult, slug = slug)
			user = Doctor.objects.get(id=request.user.id)
			vinculo, created = Doctor_consult.objects.get_or_create(doctor = user, consult = consult, patient = patient)
			messages.success(request,'Consulta criada com sucesso!')
			form = ConsultForm()
	else:
		print('Não!')
		form = ConsultForm()
	contexto['form'] = form
	return render(request, template_name,contexto)


def consults(request):
	template_name = ''
	contexto = {}
	consults = None
	try:
		doctor = Doctor.objects.get(id = request.user.id)
		consults = Doctor_consult.objects.all().filter(doctor = doctor)
		template_name = 'consult.html'
	except Exception as e:
		patient = Patient.objects.get(id = request.user.id)
		consults = Doctor_consult.objects.all().filter(patient = patient)
		template_name = 'consult_patient.html'
	contexto['consults'] = consults
	return render(request, template_name, contexto)


def details_consult(request, slug):
	template_name = ''
	context = {}
	# try:
	doctor = Doctor.objects.get(id = request.user.id)
	consult = get_object_or_404(Consult, slug = slug)
	treatment = Treatment.objects.all().filter(consult__consult = consult)
	exam = Exams.objects.all().filter(consult__consult = consult)
	print(treatment)
	template_name = 'details_consult.html'
	# except Exception as e:
	# 	patient = Patient.objects.get(id = request.user.id)
	# 	consults = Doctor_consult.objects.all().filter(patient = patient)
	# 	template_name = 'details_consult.html'
	context['slug'] = slug
	context['treatments'] = treatment
	context['exams'] = exam
	return render(request, template_name,context)

consult/templates/consult.html
{% extends 'doctor/dashboard_doctor.html' %}
{% load static %}
<html>
  <head>
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
  <style type="text/css">
    #botao{
      margin-top: -10%;
    }
  </style>
    <div class="wrapper">
      <!-- Left side column. contains the logo and sidebar -->
      {% block content %}
        {% block shortcuts %}
            {{ block.super }}
              
            <div class="col-md-12">
              <div class="box">
                <div class="box-header with-border">
                  <br>
                  <center><h3 class="box-title">Lista de consultas</h3></center>
                  <br>

                  <form class="col-md-12 col-lg-offset-10">
                  <h4>Criar consulta</h4>
                    <div class="input-group">
                      <div class="input-group-btn">
                        <a href="{% url 'consult:create_consult' %}"><button class="btn btn-success" type="button"><i class="fa fa-plus"></i></button></a>
                      </div>
                    </div>
                  </form>

                </div><!-- /.box-header -->
                {% for consult in consults %}
                <div class="box-body">
                  <table class="table table-bordered">
                    <tr>
                      <th>Paciente</th>
                      <th>Tipo de consulta</th>
                      <th>Médico</th>
                      <th>Data e Hora</th>
                      <th>Hospital</th>
                      <th>Mais informações</th>
                    </tr>
                    <tr>
                      <td>{{consult.patient}}</td>
                      <td>{{consult.consult.consult_type}}</td>
                      <td>{{consult.doctor}}</td>
                      <td><span class="badge bg-red">{{consult.created_at}}</span></td>
                      <td>{{consult.consult.hospital}}</td>
                      <td>
                        <div class="input-group">
                          <div class="input-group-btn">
                            <a href="{% url 'consult:details_consult' consult.consult.slug %}"><button class="btn btn-success" type="button">Ver detahes</button></a>
                          </div>
                        </div>
                      </td>
                    </tr>
                  </table>
                </div><!-- /.box-body -->
                {% endfor %}
                <div class="box-footer clearfix">
                  <ul class="pagination pagination-sm no-margin pull-right">
                    <li><a href="#">&laquo;</a></li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">&raquo;</a></li>
                  </ul>
                </div>
              </div><!-- /.box -->
            </div><!-- /.col -->

            </div>
            </div>
        {% endblock %}
      {% endblock %}
    </div><!-- ./wrapper -->

  </body>
</html>

consult/templates/consult_patient.html
{% extends 'patient/dashboard_patient.html' %}
{% load static %}
<html>
  <head>
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
  <style type="text/css">
    #botao{
      margin-top: -10%;
    }
  </style>
    <div class="wrapper">
      <!-- Left side column. contains the logo and sidebar -->
      {% block content %}
        {% block shortcuts %}
            {{ block.super }}
              
            <div class="col-md-12">
              <div class="box">
                <div class="box-header with-border">
                  <br>
                  <center><h3 class="box-title">Lista de suas consultas</h3></center>
                  <br>

                </div><!-- /.box-header -->
                {% for consult in consults %}
                <div class="box-body">
                  <table class="table table-bordered">
                    <tr>
                      <th>Paciente</th>
                      <th>Tipo de consulta</th>
                      <th>Médico</th>
                      <th>Data e Hora</th>
                      <th>Hospital</th>
                      <th>Mais informações</th>
                    </tr>
                    <tr>
                      <td>{{consult.patient}}</td>
                      <td>{{consult.consult_type}}</td>
                      <td>{{consult.doctor}}</td>
                      <td><span class="badge bg-red">{{consult.created_at}}</span></td>
                      <td>{{consult.hospital}}</td>
                      <td>
                        <div class="input-group">
                          <div class="input-group-btn">
                            <a href="{{ consult.get_absolute_url }}"><button class="btn btn-success" type="button">Ver detahes</button></a>
                          </div>
                        </div>
                      </td>
                    </tr>
                  </table>
                </div><!-- /.box-body -->
                {% endfor %}
                <div class="box-footer clearfix">
                  <ul class="pagination pagination-sm no-margin pull-right">
                    <li><a href="#">&laquo;</a></li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">&raquo;</a></li>
                  </ul>
                </div>
              </div><!-- /.box -->
            </div><!-- /.col -->

            </div>
            </div>
        {% endblock %}
      {% endblock %}
    </div><!-- ./wrapper -->

  </body>
</html>

consult/templates/create_consult.html
{% extends 'doctor/dashboard_doctor.html' %}
{% load static %}
{% load widget_tweaks %}
<html>
  <head>
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
  <style type="text/css">

  </style>
    <div class="wrapper">
      <!-- Left side column. contains the logo and sidebar -->
      {% block content %}
        {% block shortcuts %}
            {{ block.super }}
              
            <div class="col-md-12">
              <div class="box">
                <div class="box-header with-border">
                  <br>
                  <center><h3 class="box-title">Criar de consultas</h3></center>
                  <br>
                </div><!-- /.box-header -->

              </div><!-- /.box -->
            </div><!-- /.col -->
            <div class="col-md-12">
            {% if messages %}
              {% for message in messages %}
                <div class="ale" >
                    <h4><div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <center>{{ message|safe }}</center>
                  </div>
                  </h4>
                  </div>
              {% endfor %}
            {% endif %}
              <div class="box box-primary">
                  <div class="box-header with-border">
                    <h3 class="box-title">Coloque os dados da consulta</h3>
                  </div><!-- /.box-header -->
                  <!-- form start -->
                  <form method="post">{% csrf_token %}
                    <div class="box-body">
                      <div class="form-group">
                        <label for="exampleInputEmail1">Código da Consulta</label>
                        {{ form.non_field_errors }}
                        {{ form.consult_code|attr:"type:text"|attr:"placeholder:Código da consulta"|add_class:"form-control"}}
                        {{ form.consult.consult_code.errors|add_error_class:"error-border"}}
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Tipo de Consulta</label>
                        {{ form.non_field_errors }}
                        {{ form.consult_type|attr:"type:text"|attr:"placeholder:Tipo de consulta"|add_class:"form-control"}}
                        {{ form.consult.consult_type.errors|add_error_class:"error-border"}}
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Hospital</label>
                        {{ form.non_field_errors }}
                        <br>
                        <input id="id_hospital" type="text" name="hospital", maxlength="50" class="form-control" placeholder="Hospital"></input>
                        {{ form.hospital.errors|add_error_class:"error-border"}}
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Médico</label>
                        {{ form.non_field_errors }}
                        {{ form.doctor|attr:"type:select"|attr:"placeholder:Tipo de consulta"|add_class:"form-control"}}
                        {{ form.doctor.errors|add_error_class:"error-border"}}
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Paciente</label>
                        {{ form.non_field_errors }}
                        {{ form.patient|attr:"type:select"|attr:"placeholder:Tipo de consulta"|add_class:"form-control"}}
                        {{ form.patient.errors|add_error_class:"error-border"}}
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Mais informações</label>
                        {{ form.non_field_errors }}
                        <br>
                        <input id="id_about" type="text", name="about", maxlength="100" class="form-control" placeholder="Mais informações">
                        </input>
                        {{ form.consult.about.errors|add_error_class:"error-border"}}
                      </div>
                      
                    </div><!-- /.box-body -->
                    <div class="box-footer">
                      <button type="submit" class="btn btn-primary">Criar</button>
                    </div>
                  </form>
                </div><!-- /.box -->
              </div>
              </div>
            </div>
        {% endblock %}
      {% endblock %}
    </div><!-- ./wrapper -->

  </body>
</html>

consult/templates/details_consult.html
{% extends 'doctor/dashboard_doctor.html' %}
{% load static %}
<html>
  <head>
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
  <style type="text/css">
    #botao{
      margin-top: -10%;
    }
    #itemt{
      box-shadow: 0px 1px 1px rgba(0, 0, 0, 0.1);
      border-radius: 3px;
      margin-top: 0px;
      background: #F5932E none repeat scroll 0% 0%;
      color: #444;
      margin-left: 60px;
      margin-right: 15px;
      padding: 0px;
      position: relative;
    }
    #nome{
      color: #FFF;
      font-size: 16px;
      line-height: 1.1;
    }
  </style>
    <div class="wrapper">
      <!-- Left side column. contains the logo and sidebar -->
      {% block content %}
        {% block shortcuts %}
            {{ block.super }}
              
            <div class="col-md-12">
              <div class="box">
                <div class="box-header with-border">
                  <br>
                  <center><h3 class="box-title">Consulta: {{slug}} - Todos os registros dessa consulta</h3></center>
                  <br>

                  <form class="col-md-12 col-lg-offset-10">
                  <h4>Criar registro</h4>
                    <div class="input-group">
                      <div class="input-group-btn">
                        <a href="{% url 'register:choice_register' slug %}"><button class="btn btn-success" type="button"><i class="fa fa-plus"></i></button></a>
                      </div>
                    </div>
                  </form>

                </div><!-- /.box-header -->
                <br>

                <div class="col-md-12">
                  <ul class="timeline">
                    <li>
                      <div class="timeline-item" id="itemt">
                        <h3 class="timeline-header no-border" id="nome"><center>Exames</center></h3>
                      </div>
                    </li>
                  </ul>
                </div>

                {% for exam in exams %}
                <div class="box-body">
                  <table class="table table-bordered">
                    <tr>
                      <th>Código do exame</th>
                      <th>Data e hora da criação</th>
                      <th>Médico que criou</th>
                      <th>Hospital</th>
                      <th>Mais informações</th>
                    </tr>
                    <tr>
                      <td>{{exam.register_code}}</td>
                      <td><span class="badge bg-red">{{exam.created_at}}</span></td>
                      <td>{{exam.consult.doctor.name}}</td>
                      <td>{{exam.consult.consult.hospital}}</td>
                      <td>
                        <div class="input-group">
                          <div class="input-group-btn">
                            <a href="{% url 'register:details_exam' exam.slug %}"><button class="btn btn-success" type="button">Ver detahes</button></a>
                          </div>
                        </div>
                      </td>
                    </tr>
                  </table>
                </div><!-- /.box-body -->
                {% empty %}
					<aside class="col-xs-10 col-xs-offset-1 espaco">
						<center><p><h5>Essa consulta ainda não possui nenhum Exame</h5></p></center>
                      <br>
                      <br>
					</aside>
                {% endfor %}

                <br>
                <div class="col-md-12">
                  <ul class="timeline">
                    <li>
                      <div class="timeline-item">
                        <h3 class="timeline-header no-border"><center>Tratamentos</center></h3>
                      </div>
                    </li>
                  </ul>
                </div>
                {% for treatment in treatments %}
                <div class="box-body">
                  <table class="table table-bordered">
                    <tr>
                      <th>Código do tratamento</th>
                      <th>Data e hora da criação</th>
                      <th>Médico que criou</th>
                      <th>Hospital</th>
                      <th>Mais informações</th>
                    </tr>
                    <tr>
                      <td>{{treatment.register_code}}</td>
                      <td><span class="badge bg-red">{{treatment.created_at}}</span></td>
                      <td>{{treatment.consult.doctor.name}}</td>
                      <td>{{treatment.consult.consult.hospital}}</td>
                      <td>
                        <div class="input-group">
                          <div class="input-group-btn">
                            <a href="{% url 'register:details_treatment' treatment.slug %}"><button class="btn btn-success" type="button">Ver detahes</button></a>
                          </div>
                        </div>
                      </td>
                    </tr>
                  </table>
                </div><!-- /.box-body -->
                {% empty %}
					<aside class="col-xs-10 col-xs-offset-1 espaco">
						<center><p><h5>Essa consulta ainda não possui nenhum Tratamento</h5></p></center>
                      <br>
                      <br>
					</aside>
                {% endfor %}
                <div class="box-footer clearfix">
                  <ul class="pagination pagination-sm no-margin pull-right">
                    <li><a href="#">&laquo;</a></li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">&raquo;</a></li>
                  </ul>
                </div>
              </div><!-- /.box -->
            </div><!-- /.col -->

            </div>
            </div>
        {% endblock %}
      {% endblock %}
    </div><!-- ./wrapper -->

  </body>
</html>