DocTr/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('core.urls', namespace='core')),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^consultas/', include('consult.urls', namespace='consult')),
    url(r'^registros/', include('register.urls', namespace='register')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

accounts/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = patterns('',...)

urlpatterns = [
    
    url(r'^$', 'accounts.views.dashboard', name='dashboard'),
    url(r'^seu_perfil', 'accounts.views.profile', name='profile'),
    url(r'^editar_perfil', 'accounts.views.edit_profile', name='edit_profile'),
    url(r'^recuperar_senha', 'accounts.views.password_reset', name='password_reset'),
    url(r'^recuperar_senha_confirmacao', 'accounts.views.password_reset_confirm', name='password_reset_confirm'),
    url(r'^lista_pacientes', 'accounts.views.patients_list', name='patients_list'),
    url(r'^lista_pacientes_medico', 'accounts.views.patients_doctor', name='patients_doctor'),
    url(r'^adiconar_paciente', 'accounts.views.add_patient', name='add_patient'),
    url(r'^medicamentos', 'accounts.views.medication', name='medication'),
    url(r'^editar_senha/$', 'accounts.views.edit_password', name = 'edit_password'),


]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = patterns('',...)

urlpatterns = [
    
    url(r'^$', 'core.views.home', name='home'),
    url(r'^rest', 'core.views.rest', name='rest'),
    url(r'^cadastrar_medico', 'core.views.register_doctor', name='register_doctor'),
    url(r'^cadastrar_pacitente', 'core.views.register_patient', name='register_patient'),
    url(r'^escolha_cadastro', 'core.views.choice_register', name='choice_register'),
    url(r'^login', 'django.contrib.auth.views.login',{'template_name': 'login.html'}, name='login'),
    url(r'^sair/$', 'django.contrib.auth.views.logout',{'next_page': 'core:login'}, name='logout'),
    url(r'^favicon\.ico$', RedirectView.as_view(url='{{STATIC_URL}}/assets/img/icon.png'))
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

register/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = patterns('',...)

urlpatterns = [
    url(r'^$', 'register.views.registers', name='registers'),
    url(r'^criar_exames_consulta(?P<slug>[\w_-]+)', 'register.views.creat_register_consult_exams', name='creat_register_consult_exams'),
    url(r'^criar_tratamento_consulta(?P<slug>[\w_-]+)', 'register.views.creat_register_consult_treatments', name='creat_register_consult_treatments'),
    url(r'^(?P<slug>[\w_-]+)/escolha_registro', 'register.views.choice_register', name='choice_register'),
   	url(r'^(?P<slug>[\w_-]+)/exames', 'register.views.exams', name='exams'),
   	url(r'^(?P<slug>[\w_-]+)/tratamentos', 'register.views.treatments', name='treatments'),
    url(r'^registros_da_consulta', 'register.views.consult_register', name='consult_register'),
    url(r'^(?P<slug>[\w_-]+)/registro_detalhe', 'register.views.details_register', name='details_register'),
    url(r'^(?P<slug>[\w_-]+)/exame_detalhe', 'register.views.details_exams', name='details_exam'),
    url(r'^(?P<slug>[\w_-]+)/tratamento_detalhe', 'register.views.details_treatments', name='details_treatment'),



]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

register/forms.py
# -*- coding: utf8 -*-
from django import forms
from .models import *
# SIGNALS
from django.db.models import signals
from django.template.defaultfilters import slugify
from accounts.models import *
import datetime
import DocTr.settings

class RegisterFormExams(forms.ModelForm):

	class Meta:
		model = Exams
		fields = ['about', 'result', 'register_code']

class RegisterFormTreatments(forms.ModelForm):

	class Meta:
		model = Treatment
		fields = ['about', 'medicine', 'register_code']

# class Edit_EventoForm(forms.ModelForm):

# 	def evento_pre_save(signal, instance, sender, **kwargs):
# 		instance.slug = slugify(instance.name)
# 	signals.pre_save.connect(evento_pre_save, sender = Evento)

# 	def clean_valor(self):
# 		valor = self.cleaned_data['valor']
# 		if valor <= 0:
# 			raise forms.ValidationError('O valor não pode ser menor ou igual a zero')
# 		return  valor
# 	class Meta:
# 		model = Evento
# 		fields = ['name', 'place_event','date_event','date_event_finsh','start_date_errolment',
# 			'finsh_date_enrrolment','image','about','valor', 'pares']

accounts/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from accounts.forms import EditAccountForm_Doctor
from django.contrib.auth.forms import (UserCreationForm, PasswordChangeForm, SetPasswordForm)
from .forms import * 
from django.conf import settings
from django.contrib.auth import authenticate, login, get_user_model
from django.template import Context, loader
from .models import *
from consult.models import *
from core.utils import generate_hash_key
from datetime import date
import datetime

User = get_user_model()

@login_required(redirect_field_name='login_obrigatorio')
def dashboard(request):
	template_name = ''
	context = {}

	try:
		doctor = Doctor.objects.get(id = request.user.id)
		patients = Doctor_consult.objects.all().filter(doctor = doctor).order_by('consult__date_consult')[:8]
		context['patients'] = patients
		template_name = 'doctor/dashboard_doctor.html'

	except Exception as e:
		template_name = 'patient/dashboard_patient.html'
	
	return render(request, template_name, context)

@login_required(redirect_field_name='login_obrigatorio')
def profile(request):
	template_name = ''
	context = {}

	try:
		doctor = Doctor.objects.get(id = request.user.id)
		template_name = 'doctor/profile.html'

	except Exception as e:
		template_name = 'patient/profile.html'
	
	return render(request, template_name, context)

@login_required(redirect_field_name='login_obrigatorio')
def edit_profile(request):
	template_name = ''
	context = {}

	try:
		doctor = Doctor.objects.get(id = request.user.id)
		template_name = 'doctor/edit_profile.html'
		form = EditAccountForm_Doctor()
		if request.method == "POST":
			form = EditAccountForm_Doctor(request.POST, request.FILES, instance = request.user)
			if form.is_valid():
				form.save()
				messages.success(request, 'Seus dados foram alterados com sucesso')
		else:
			form = EditAccountForm_Doctor(instance = request.user)
		context['form'] = form

	except Exception as e:

		template_name = 'patient/edit_profile.html'
		form = EditAccountForm_Patient()
		if request.method == "POST":
			form = EditAccountForm_Patient(request.POST, request.FILES, instance = request.user)
			if form.is_valid():
				form.save()
				messages.success(request, 'Seus dados foram alterados com sucesso')
		else:
			form = EditAccountForm_Patient(instance = request.user)
		context['form'] = form
	
	return render(request, template_name, context)

	
@login_required(redirect_field_name='login_obrigatorio')
def add_patient(request):

	template_name = 'doctor/add_patient.html'
	form = RegisterForm_Patient(request.POST)
	contexto = {}
	if request.method == "POST":
		if form.is_valid():
			user = form.save()
			messages.success(request, 'Cadastro do paciente feito com sucesso!')
			user.save()
	else:
		form = RegisterForm_Patient()
	contexto['form'] = form
	return render(request, template_name, contexto)

@login_required(redirect_field_name='login_obrigatorio')
def patients_list(request):
	patients = Patient.objects.all()
	context = {
		'patients':patients
	}
	template_name = 'doctor/patients_list.html'
	return render(request, template_name, context)

@login_required(redirect_field_name='login_obrigatorio')
def patients_doctor(request):
	doctor = Doctor.objects.get(id = request.user.id)
	patients_doctor = Doctor_consult.objects.all().filter(doctor = doctor)
	context = {
		'patients_doctor':patients_doctor
	}
	template_name = 'doctor/patients_doctor.html'
	return render(request, template_name, context)

@login_required(redirect_field_name='login_obrigatorio')
def medication(request):
	template_name = 'doctor/medication.html'
	return render(request, template_name)

@login_required(redirect_field_name='login_obrigatorio')
def edit_password(request):

	template_name = ''
	context = {}
	try:
		doctor = Doctor.objects.get(id = request.user.id)
		template_name = 'doctor/edit_password.html'

	except Exception as e:

		template_name = 'patient/edit_password.html'

	if request.method == 'POST':
		form = PasswordChangeForm(data = request.POST, user = request.user)
		if form.is_valid():
			MIN_LENGTH = 8
			password1 = form.cleaned_data['new_password1']

			# At least one letter and one non-letter
			first_isalpha = password1[0].isalpha()
			if all(c.isalpha() == first_isalpha for c in password1):
				messages.success(request,'A senha deve conter pelo menos uma letra e pelo menos um dígito ou "\
				"um caractere de pontuação.')
				form = PasswordChangeForm(data = request.POST, user = request.user)
			# At least MIN_LENGTH long
			elif len(password1) < MIN_LENGTH:
				messages.success(request,'A senha deve ter %d caracteres no mínimo.' % MIN_LENGTH)
				form = PasswordChangeForm(data = request.POST, user = request.user)
			else:
				form.save()
				contexto['success'] = True
				messages.success(request, 'Sua senha foi alterada com sucesso!')
	else:
		form = PasswordChangeForm(user = request.user)
	context['form'] = form
	
	return render(request, template_name, context)


'''
	Método para resetar a senha, para quando um usuário ainda NÃO logado esquece a senha.
'''
def password_reset(request):
	template_name = 'doctor/password_reset.html'
	contexto = {}
	form = PasswordResetForm(request.POST or None)

	if form.is_valid():
		form.save()
		contexto['success'] = True
		messages.success(request,'Um e-mail foi enviando para você, verifique sua caixa de entrada')
	contexto['form'] = form

	return render(request, template_name, contexto)

'''
	Antes de entrar nesse método, um email é enviado para o usuário e ele recebe um link que redireciona
	para esse método, que é o método que vai gerar uma nova senha para o usuário.

'''
def password_reset_confirm(request, key):
	template_name = 'doctor/password_reset_confirm.html'
	contexto = {}
	reset = get_object_or_404(PasswordReset, key = key)
	form = SetPasswordForm(user = reset.user, data = request.POST or None)
	if form.is_valid():
		MIN_LENGTH = 8
		password1 = form.cleaned_data['new_password1']

		# At least one letter and one non-letter
		first_isalpha = password1[0].isalpha()
		if all(c.isalpha() == first_isalpha for c in password1):
			messages.success(request,'A senha deve conter pelo menos uma letra e pelo menos um dígito ou "\
			"um caractere de pontuação.')
			form = SetPasswordForm(user = reset.user, data = request.POST)
		# At least MIN_LENGTH long
		elif len(password1) < MIN_LENGTH:
			messages.success(request,'A senha deve ter %d caracteres no mínimo.' % MIN_LENGTH)
			form = SetPasswordForm(user = reset.user, data = request.POST)
		else:
			form.save()
			contexto['success'] = True
			messages.success(request,'Sua senha foi criada com sucesso')
	contexto['form'] = form

	return render(request,template_name,contexto)

register/views.py
# -*- coding: utf8 -*-
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.http import HttpResponseRedirect
from .models import *
from accounts.models import *
from consult.models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import *
from django.contrib.auth import get_user
import datetime
import copy
from .models import *
# SIGNALS AND LISTENERS
from django.contrib.auth.models import User
from django.db.models import signals
from django.dispatch import dispatcher
# EXTRAS
from datetime import date


@login_required(redirect_field_name='login_obrigatorio')
def creat_register_consult_exams(request,slug):
	
	template_name = 'creat_register_consult_exams.html'
	consult = get_object_or_404(Consult, slug = slug)
	form = RegisterFormExams(request.POST, request.FILES)
	contexto = {}
	if request.method == "POST":
		if form.is_valid():
			newform = form.save(commit=False)
			newform.user = request.user
			newform.consult = consult
			newform.register_code = newform.register_code + 1
			newform.save()
			messages.success(request,'Exame criado com sucesso!')
			form = RegisterFormExams()
	else:
		print('Não')
		form = RegisterFormExams()
	contexto['form'] = form
	contexto['hospital'] = consult.hospital
	contexto['doctor'] = consult.doctor
	contexto['patient'] = consult.patient
	contexto['consult'] = consult
	contexto['slug'] = slug
	return render(request, template_name,contexto)

@login_required(redirect_field_name='login_obrigatorio')
def creat_register_consult_treatments(request,slug):

	template_name = 'creat_register_consult_treatments.html'
	consult = get_object_or_404(Consult, slug = slug)
	form = RegisterFormTreatments(request.POST, request.FILES)
	contexto = {}
	if request.method == "POST":
		if form.is_valid():
			newform = form.save(commit=False)
			newform.user = request.user
			newform.consult = consult
			newform.register_code = newform.register_code + 1
			newform.save()
			messages.success(request,'Tratamento criado com sucesso!')
			form = RegisterFormTreatments()
	else:
		print('Não')
		form = RegisterFormTreatments()
	contexto['form'] = form
	contexto['hospital'] = consult.hospital
	contexto['doctor'] = consult.doctor
	contexto['patient'] = consult.patient
	contexto['consult'] = consult
	contexto['slug'] = slug
	return render(request, template_name,contexto)

@login_required(redirect_field_name='login_obrigatorio')
def registers(request):
	template_name = ''
	contexto = {}
	consults = None
	try:
		doctor = Doctor.objects.get(id = request.user.id)
		registers = Register.objects.all()
		template_name = 'registers.html'
	except Exception as e:
		patient = Patient.objects.get(id = request.user.id)
		registers = Doctor_consult.objects.all().filter(patient = patient)
		print('Paciente Registro')
		template_name = 'register_patient.html'
	contexto = {
		'registers':registers
	}
	return render(request, template_name, contexto)

@login_required(redirect_field_name='login_obrigatorio')
def consult_register(request):
	consult_register = Register.objects.all()
	template_name = 'consult_register.html'
	contexto = {
		'consult_register':consult_register
	}
	return render(request, template_name, contexto)

@login_required(redirect_field_name='login_obrigatorio')
def details_register(request, slug):
    template_name = 'details_register.html'
    context = {
    	'slug': slug
    }
    return render(request, template_name,context)

@login_required(redirect_field_name='login_obrigatorio')
def choice_register(request, slug):
    template_name = 'choice_register.html'
    context = {
    	'slug': slug
    }
    return render(request, template_name,context)

@login_required(redirect_field_name='login_obrigatorio')
def exams(request, slug):
    template_name = 'exams.html'
    exams = Exams.objects.all()
    context = {
    	'exams':exams,
    	'slug':slug
    }
    return render(request, template_name,context)
@login_required(redirect_field_name='login_obrigatorio')
def treatments(request, slug):
    template_name = 'treatments.html'
    treatments = Treatment.objects.all()
    context = {
    	'treatments':treatments,
    	'slug':slug
    }
    return render(request, template_name,context)

@login_required(redirect_field_name='login_obrigatorio')
def details_treatments(request, slug):
	template_name = 'details_treatments.html'
	treatments = get_object_or_404(Treatment,slug = slug)
	context = {
		'slug': slug,
		'treatment': treatments
	}
	return render(request, template_name,context)

@login_required(redirect_field_name='login_obrigatorio')
def details_exams(request, slug):

	exams = get_object_or_404(Exams,slug = slug)
	template_name = 'details_exams.html'
	context = {
		'slug': slug,
		'exam':exams
	}
	return render(request, template_name,context)

accounts/templates/doctor/edit_password.html
{% extends 'doctor/profile.html' %}
{% load static %}
{% load widget_tweaks %}
<html>
  <head>
    <meta charset="UTF-8">
    <title>AdminLTE 2 | User Profile</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <style type="text/css">

    .errorlist{
      list-style: none;
      color: red;
      margin-left: -12%;
    }

  </style>
    <div class="wrapper">
      <!-- Left side column. contains the logo and sidebar -->
      
      {% block content %}
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
      {% block content_header %}
        {{block.super}}
      {% endblock %}
      {% block content_left_profile %}
        {{block.super}}
      {% endblock %}
      {% block content_right_profile %}
        <div class="col-md-9">
          <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
              <li><a href="{% url 'accounts:profile' %}">Início</a></li>
              <li><a href="{% url 'accounts:edit_profile' %}">Editar Perfil</a></li>
              <li class="active"><a href="{% url 'accounts:edit_password' %}">Editar Senha</a></li>
            </ul>
            
            <div class="tab-content">
              <div class="active tab-pane" id="settings">
                  <form class="form-horizontal" method="post">{% csrf_token %}
                  {% if messages %}
                    {% for message in messages %}
                      <div class="ale" >
                          <h4><div class="alert alert-success">
                          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                          <center>{{ message|safe }}</center>
                        </div>
                        </h4>
                        </div>
                    {% endfor %}
                  {% endif %}
                  <div class="form-group">
                    <label for="inputSkills" class="col-sm-2 control-label">Senha Antiga</label>
                    <div class="col-sm-10">
                      {{ form.non_field_errors }}
                      {{ form.old_password|attr:"type:password"|attr:"placeholder:Senha Antiga"|add_class:"form-control"}}
                      {{ form.old_password.errors|add_error_class:"error-border"}}
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputSkills" class="col-sm-2 control-label">Nova Senha</label>
                    <div class="col-sm-10">
                      {{ form.non_field_errors }}
                      {{ form.new_password1|attr:"type:password"|attr:"placeholder:Nova Senha"|add_class:"form-control"}}
                      {{ form.new_password1.errors|add_error_class:"error-border"}}
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputSkills" class="col-sm-2 control-label">Confirmação da Nova Senha</label>
                    <div class="col-sm-10">
                      {{ form.non_field_errors }}
                      {{ form.new_password2|attr:"type:password"|attr:"placeholder:Confirmação da Nova Senha"|add_class:"form-control"}}
                      {{ form.new_password2.errors|add_error_class:"error-border"}}
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                      <button type="submit" class="btn btn-danger">Editar</button>
                    </div>
                  </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
          </div>
      {% endblock %}
      </div><!-- /.content-wrapper -->
      {% endblock %}
    </div><!-- ./wrapper -->

    <!-- jQuery 2.1.4 -->
    <script src="{% static 'plugins/jQuery/jQuery-2.1.4.min.js' %}"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'plugins/fastclick/fastclick.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/app.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}"></script>
  </body>
</html>

accounts/templates/doctor/register.html
{% load static %}
{% load widget_tweaks %}
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Doc.Tr | Cadastro</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'plugins/iCheck/square/blue.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="hold-transition register-page">
  <style type="text/css">

    .errorlist{
      list-style: none;
      color: #E94A4A;
      margin-left: -12%;
    }
    .login-page, .register-page {
        background: #FFF none repeat scroll 0% 0%;
        background-color: #FFF;
        background-image: none;
        background-repeat: repeat;
        background-attachment: scroll;
        background-position: 0% 0%;
        background-clip: border-box;
        background-origin: padding-box;
        background-size: auto auto;
    }
  .login-box-body, .register-box-body {
    background: #00415E none repeat scroll 0% 0%;

    }
    .login-box-body, .register-box-body{
      color: white;
    }
    .btn-primary{
      background-color: #F5932E;
      border-color: #F5932E;
    }
    .btn-primary:hover{
      background-color: #D8842D;
      border-color: #D8842D;
    }
    a{
      color: white;
    }
    a:hover{
      color: #D8842D;
    }
    #logo{
      width: 65%;
    }

  </style>
    <div class="register-box">
      <div class="register-logo">
        <div class="row">
          <img  class="col-lg-12 col-lg-offset-2" src="{% static 'img/logo.png' %}" id="logo">
        </div>
        <br>
      </div>

      <div class="register-box-body">
        <p class="login-box-msg">Cadastre - se</p>
        <form method="post"> {% csrf_token %}
          {% if messages %}
            {% for message in messages %}
              <div class="ale" >
                  <h4><div class="alert alert-success">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <center>{{ message|safe }}</center>
                </div>
                </h4>
                </div>
            {% endfor %}
          {% endif %}
          <div class="form-group has-feedback">
              {{ form.non_field_errors }}
              {{ form.username|attr:"type:text"|attr:"placeholder:Nome de usuário"|add_class:"form-control"}}
              {{ form.username.errors|add_error_class:"error-border"}}
            <span class="glyphicon glyphicon-user form-control-feedback"></span>
          </div>
          <div class="form-group has-feedback">
              {{ form.non_field_errors }}
              {{ form.email|attr:"type:email"|attr:"placeholder:E-mail"|add_class:"form-control"}}
              {{ form.email.errors|add_error_class:"error-border"}}
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
          </div>
          <div class="form-group has-feedback">
              {{ form.non_field_errors }}
              {{ form.crm|attr:"type:text"|attr:"placeholder:CRM"|add_class:"form-control"}}
              {{ form.crm.errors|add_error_class:"error-border"}}
            <span class="fa fa-medkit form-control-feedback"></span>
          </div>
          <div class="form-group has-feedback">
              {{ form.non_field_errors }}
              {{ form.phone|attr:"type:text"|attr:"placeholder:Telefone"|add_class:"form-control"}}
              {{ form.phone.errors|add_error_class:"error-border"}}
            <span class="fa fa-phone form-control-feedback"></span>
          </div>
          <div class="form-group has-feedback">
              {{ form.non_field_errors }}
              {{ form.password1|attr:"type:password"|attr:"placeholder:Senha"|add_class:"form-control"}}
              {{ form.password1.errors|add_error_class:"error-border"}}
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
          </div>
          <div class="form-group has-feedback">
              {{ form.non_field_errors }}
              {{ form.password2|attr:"type:password"|attr:"placeholder:Confirmação de Senha"|add_class:"form-control"}}
              {{ form.password2.errors|add_error_class:"error-border"}}
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
          </div>
          <div class="row">
            <div class="col-xs-4">
              <button type="submit" class="btn btn-primary btn-block btn-flat">Cadastrar</button>
            </div><!-- /.col -->
          </div>
        </form>

        <a href="{% url 'core:login' %}" class="text-center">Eu já tenho cadastro!</a><br>
        <a href="{% url 'core:choice_register' %}" class="text-center">Voltar a escolher</a>
      </div><!-- /.form-box -->
    </div><!-- /.register-box -->

    <!-- jQuery 2.1.4 -->
    <script src="{% static 'plugins/jQuery/jQuery-2.1.4.min.js' %}"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- iCheck -->
    <script src="{% static 'plugins/iCheck/icheck.min.js' %}"></script>
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>
  </body>
</html>